# Schema for the configuration files of the Historical Timeline module.
historical_timeline.settings:
  type: config_object
  label: 'Historical Timeline settings'
  mapping:
    example:
      type: string
      label: 'Example'
